(part "EC12D1524403"
    (packageRef "EC12D1524403")
    (interface
        (port "A1" (symbPinId 1) (portName "A1") (portType INOUT))
        (port "B1" (symbPinId 2) (portName "B1") (portType INOUT))
        (port "C1" (symbPinId 3) (portName "C1") (portType INOUT))
        (port "D1" (symbPinId 4) (portName "D1") (portType INOUT))
        (port "E1" (symbPinId 5) (portName "E1") (portType INOUT))
        (port "MH1" (symbPinId 6) (portName "MH1") (portType INOUT))
        (port "MH2" (symbPinId 7) (portName "MH2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "688-EC12D1524403")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Alps-Alpine/EC12D1524403?qs=6EGMNY9ZYDSnlYGJrjCewg%3D%3D")
    (property "Manufacturer_Name" "ALPS Electric")
    (property "Manufacturer_Part_Number" "EC12D1524403")
    (property "Description" "17,5mm Vertical encoder 15 Pulses 30 DET")
    (property "Datasheet_Link" "https://www.alps.com/prod/info/E/HTML/Encoder/Incremental/EC12E/EC12D1524403.html")
    (property "symbolName1" "EC12D1524403")
)
